"""add_legacy_fields_to_inventario

Revision ID: 137c2a154ad0
Revises: 20c00f17909a
Create Date: 2026-04-19 13:16:29.311163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137c2a154ad0'
down_revision: Union[str, None] = '20c00f17909a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventario_repuestos', sa.Column('min_stock', sa.Integer(), nullable=False))
    op.add_column('repuestos', sa.Column('sku', sa.String(length=30), server_default='TBD', nullable=False))
    op.add_column('repuestos', sa.Column('system_category', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_repuestos_sku'), 'repuestos', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repuestos_sku'), table_name='repuestos')
    op.drop_column('repuestos', 'system_category')
    op.drop_column('repuestos', 'sku')
    op.drop_column('inventario_repuestos', 'min_stock')
    # ### end Alembic commands ###
