"""add_legacy_fields_to_solicitud

Revision ID: 20c00f17909a
Revises: 8613f1b99d5e
Create Date: 2026-04-19 13:13:20.332968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c00f17909a'
down_revision: Union[str, None] = '8613f1b99d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_servicio', sa.Column('code', sa.String(length=20), server_default='TBD', nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('ubicacion', sa.String(length=200), server_default='Ubicación desconocida', nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('prioridad', sa.String(length=10), nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('progreso', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_solicitudes_servicio_code'), 'solicitudes_servicio', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_servicio_code'), table_name='solicitudes_servicio')
    op.drop_column('solicitudes_servicio', 'progreso')
    op.drop_column('solicitudes_servicio', 'prioridad')
    op.drop_column('solicitudes_servicio', 'ubicacion')
    op.drop_column('solicitudes_servicio', 'code')
    # ### end Alembic commands ###
