"""agregar_tablas_legacy_service_requests

Revision ID: 5be15331446e
Revises: 137c2a154ad0
Create Date: 2026-04-19 17:09:33.389467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be15331446e'
down_revision: Union[str, None] = '137c2a154ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('vehicle_info', sa.String(length=200), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assigned_mechanic', sa.String(length=100), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_code'), 'service_requests', ['code'], unique=True)
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.drop_column('inventario_repuestos', 'min_stock')
    op.drop_index('ix_repuestos_sku', table_name='repuestos')
    op.drop_column('repuestos', 'system_category')
    op.drop_column('repuestos', 'sku')
    op.drop_index('ix_solicitudes_servicio_code', table_name='solicitudes_servicio')
    op.drop_column('solicitudes_servicio', 'prioridad')
    op.drop_column('solicitudes_servicio', 'code')
    op.drop_column('solicitudes_servicio', 'ubicacion')
    op.drop_column('solicitudes_servicio', 'progreso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_servicio', sa.Column('progreso', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('ubicacion', sa.VARCHAR(length=200), server_default=sa.text("'Ubicación desconocida'::character varying"), autoincrement=False, nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('code', sa.VARCHAR(length=20), server_default=sa.text("'TBD'::character varying"), autoincrement=False, nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('prioridad', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.create_index('ix_solicitudes_servicio_code', 'solicitudes_servicio', ['code'], unique=True)
    op.add_column('repuestos', sa.Column('sku', sa.VARCHAR(length=30), server_default=sa.text("'TBD'::character varying"), autoincrement=False, nullable=False))
    op.add_column('repuestos', sa.Column('system_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index('ix_repuestos_sku', 'repuestos', ['sku'], unique=True)
    op.add_column('inventario_repuestos', sa.Column('min_stock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_code'), table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
