"""remove legacy service_requests table

Revision ID: 726fc2dc52f3
Revises: ba54aa1a6f8a
Create Date: 2026-04-21 13:52:18.856328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '726fc2dc52f3'
down_revision: Union[str, None] = 'ba54aa1a6f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_requests_code', table_name='service_requests')
    op.drop_index('ix_service_requests_id', table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vehicle_info', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('assigned_mechanic', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name='service_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_requests_pkey')
    )
    op.create_index('ix_service_requests_id', 'service_requests', ['id'], unique=False)
    op.create_index('ix_service_requests_code', 'service_requests', ['code'], unique=True)
    # ### end Alembic commands ###
