"""remove_legacy_fields

Revision ID: 81866758a5de
Revises: 974e3da10654
Create Date: 2026-04-27 16:18:50.085544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81866758a5de'
down_revision: Union[str, None] = '974e3da10654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventario_repuestos_repuesto_id_fkey', 'inventario_repuestos', type_='foreignkey')
    op.create_foreign_key(None, 'inventario_repuestos', 'repuestos', ['repuesto_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_mecanicos_employee_code', table_name='mecanicos')
    op.drop_column('mecanicos', 'expertise')
    op.drop_column('mecanicos', 'phone')
    op.drop_column('mecanicos', 'avatar_color')
    op.drop_column('mecanicos', 'employee_code')
    op.drop_constraint('solicitud_repuestos_repuesto_id_fkey', 'solicitud_repuestos', type_='foreignkey')
    op.create_foreign_key(None, 'solicitud_repuestos', 'repuestos', ['repuesto_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_usuarios_username', table_name='usuarios')
    op.drop_column('usuarios', 'last_login')
    op.drop_column('usuarios', 'is_verified')
    op.drop_column('usuarios', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_usuarios_username', 'usuarios', ['username'], unique=True)
    op.drop_constraint(None, 'solicitud_repuestos', type_='foreignkey')
    op.create_foreign_key('solicitud_repuestos_repuesto_id_fkey', 'solicitud_repuestos', 'repuestos', ['repuesto_id'], ['id'])
    op.add_column('mecanicos', sa.Column('employee_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('mecanicos', sa.Column('avatar_color', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('mecanicos', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('mecanicos', sa.Column('expertise', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_mecanicos_employee_code', 'mecanicos', ['employee_code'], unique=True)
    op.drop_constraint(None, 'inventario_repuestos', type_='foreignkey')
    op.create_foreign_key('inventario_repuestos_repuesto_id_fkey', 'inventario_repuestos', 'repuestos', ['repuesto_id'], ['id'])
    # ### end Alembic commands ###
