"""modelo_logico_completo

Revision ID: 8613f1b99d5e
Revises: 
Create Date: 2026-04-19 11:54:09.451412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8613f1b99d5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repuestos_id'), 'repuestos', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('talleres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talleres_id'), 'talleres', ['id'], unique=False)
    op.create_table('tipos_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_servicio_id'), 'tipos_servicio', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('inventarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventarios_id'), 'inventarios', ['id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('system_category', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=True)
    op.create_table('mecanicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('especialidad', sa.String(length=50), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('expertise', sa.String(length=20), nullable=True),
    sa.Column('avatar_color', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_mecanicos_employee_code'), 'mecanicos', ['employee_code'], unique=True)
    op.create_index(op.f('ix_mecanicos_id'), 'mecanicos', ['id'], unique=False)
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('inventario_repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventarios.id'], ),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_repuestos_id'), 'inventario_repuestos', ['id'], unique=False)
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_table('solicitudes_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=True),
    sa.Column('mecanico_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servicio_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ASIGNADA', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA', 'RECHAZADA', name='estado_solicitud'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('descripcion_problema', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['mecanico_id'], ['mecanicos.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.ForeignKeyConstraint(['tipo_servicio_id'], ['tipos_servicio.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_servicio_id'), 'solicitudes_servicio', ['id'], unique=False)
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_servicio.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calificaciones_id'), 'calificaciones', ['id'], unique=False)
    op.create_table('historial_estado_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ASIGNADA', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA', 'RECHAZADA', name='estado_solicitud'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estado_solicitud_id'), 'historial_estado_solicitud', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'MERCADOPAGO', name='metodo_pago'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'COMPLETADO', 'FALLIDO', 'REEMBOLSADO', name='estado_pago'), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_servicio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('solicitud_repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('repuesto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['repuesto_id'], ['repuestos.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_repuestos_id'), 'solicitud_repuestos', ['id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('impuesto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura'),
    sa.UniqueConstraint('pago_id')
    )
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_solicitud_repuestos_id'), table_name='solicitud_repuestos')
    op.drop_table('solicitud_repuestos')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_historial_estado_solicitud_id'), table_name='historial_estado_solicitud')
    op.drop_table('historial_estado_solicitud')
    op.drop_index(op.f('ix_calificaciones_id'), table_name='calificaciones')
    op.drop_table('calificaciones')
    op.drop_index(op.f('ix_solicitudes_servicio_id'), table_name='solicitudes_servicio')
    op.drop_table('solicitudes_servicio')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_inventario_repuestos_id'), table_name='inventario_repuestos')
    op.drop_table('inventario_repuestos')
    op.drop_table('usuario_roles')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_mecanicos_id'), table_name='mecanicos')
    op.drop_index(op.f('ix_mecanicos_employee_code'), table_name='mecanicos')
    op.drop_table('mecanicos')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_inventarios_id'), table_name='inventarios')
    op.drop_table('inventarios')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_servicio_id'), table_name='tipos_servicio')
    op.drop_table('tipos_servicio')
    op.drop_index(op.f('ix_talleres_id'), table_name='talleres')
    op.drop_table('talleres')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_repuestos_id'), table_name='repuestos')
    op.drop_table('repuestos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
