"""create propietario model

Revision ID: 974e3da10654
Revises: a6134da5f455
Create Date: 2026-04-26 23:47:39.591413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974e3da10654'
down_revision: Union[str, None] = 'a6134da5f455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propietarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_propietarios_id'), 'propietarios', ['id'], unique=False)
    op.add_column('talleres', sa.Column('propietario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'talleres', 'propietarios', ['propietario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'talleres', type_='foreignkey')
    op.drop_column('talleres', 'propietario_id')
    op.drop_index(op.f('ix_propietarios_id'), table_name='propietarios')
    op.drop_table('propietarios')
    # ### end Alembic commands ###
