"""Update inventory models

Revision ID: b89b41764dc9
Revises: 021b6f42bb46
Create Date: 2026-04-21 12:40:56.719238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b89b41764dc9'
down_revision: Union[str, None] = '021b6f42bb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_items_id', table_name='inventory_items')
    op.drop_index('ix_inventory_items_sku', table_name='inventory_items')
    op.drop_table('inventory_items')
    op.add_column('inventario_repuestos', sa.Column('min_stock', sa.Integer(), nullable=False))
    op.add_column('repuestos', sa.Column('sku', sa.String(length=30), nullable=False))
    op.add_column('repuestos', sa.Column('system_category', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_repuestos_sku'), 'repuestos', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repuestos_sku'), table_name='repuestos')
    op.drop_column('repuestos', 'system_category')
    op.drop_column('repuestos', 'sku')
    op.drop_column('inventario_repuestos', 'min_stock')
    op.create_table('inventory_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('system_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_critical', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name='inventory_items_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_items_pkey')
    )
    op.create_index('ix_inventory_items_sku', 'inventory_items', ['sku'], unique=True)
    op.create_index('ix_inventory_items_id', 'inventory_items', ['id'], unique=False)
    # ### end Alembic commands ###
