"""refactor service requests to normalized model

Revision ID: ba54aa1a6f8a
Revises: b89b41764dc9
Create Date: 2026-04-21 13:51:28.359876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba54aa1a6f8a'
down_revision: Union[str, None] = 'b89b41764dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_servicio', sa.Column('codigo', sa.String(length=20), nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('prioridad', sa.String(length=10), nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('ubicacion', sa.String(length=200), nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('progreso', sa.Integer(), nullable=False))
    op.add_column('solicitudes_servicio', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_solicitudes_servicio_codigo'), 'solicitudes_servicio', ['codigo'], unique=True)
    op.create_foreign_key(None, 'solicitudes_servicio', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitudes_servicio', type_='foreignkey')
    op.drop_index(op.f('ix_solicitudes_servicio_codigo'), table_name='solicitudes_servicio')
    op.drop_column('solicitudes_servicio', 'usuario_id')
    op.drop_column('solicitudes_servicio', 'progreso')
    op.drop_column('solicitudes_servicio', 'ubicacion')
    op.drop_column('solicitudes_servicio', 'prioridad')
    op.drop_column('solicitudes_servicio', 'codigo')
    # ### end Alembic commands ###
