"""add_attachments_to_service_request

Revision ID: ef14657350dc
Revises: 81866758a5de
Create Date: 2026-04-29 10:01:40.720157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef14657350dc'
down_revision: Union[str, None] = '81866758a5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_servicio', sa.Column('url_imagen', sa.String(length=500), nullable=True))
    op.add_column('solicitudes_servicio', sa.Column('url_audio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes_servicio', 'url_audio')
    op.drop_column('solicitudes_servicio', 'url_imagen')
    # ### end Alembic commands ###
